
coverage:
  status:
    project:
      default:
        branches: 
          - main
        if_ci_failed: error #success, failure, error, ignore
        informational: false
        only_pulls: false
    patch:
      default:
        branches: 
          - main
        if_ci_failed: ignore #success, failure, error, ignore
        informational: true
        only_pulls: false
    set1:
      default:
        branches: 
          - main
        if_ci_failed: ignore #success, failure, error, ignore
        informational: true
        only_pulls: false

comment:                  # this is a top-level key
  layout: "reach, diff, flags, files"
  behavior: default

ignore:
  - "junk"  # ignore folders and all its contents